### PR TITLE
fix: dev command loading snapshot

### LINKED ISSUE #1650: bug: running dev.ts uses the snapshot
Using `deno run -A dev.ts` after building the assets I get `Using snapshot found at ..`

I expected the dev builds to not use the snapshots, and thats what the docs here https://fresh.deno.dev/docs/concepts/ahead-of-time-builds seems to say 
>When Fresh is started in **non-development** mode (usually via main.ts), Fresh will automatically pick up optimized assets

### PR DESCRIPTION
**Pull request by marvinhagemeister**
This PR changes the `dev.ts` script so that it doesn't import `main.ts` anymore if the new `config` parameter was passed. This changes the architecture in that the `dev` mode doesn't sit on top of `main` anymore which allows us to properly detect if we're in dev mode without other means. By calling into `ServerContext` directly instead of somewhere abstracted away behind `start` we can set all options ourselves, like if we want to skip loading the snapshot or not.

Note that this still preserves the previous behavior when no `fresh.config.ts` file is used. So this isn't a breaking change.

Fixes #1650

### CODE REVIEW

File: src/dev/dev_command.ts [hunk 1]
```diff
@@ -34,9 +39,28 @@ export async function dev(
 
   if (manifestChanged) await generate(dir, newManifest);
 
-  if (Deno.args.includes("build")) {
+  const manifest = (await import(toFileUrl(join(dir, "fresh.gen.ts")).href))
+    .default as ServerManifest;
```
Comment (bartlomieju) [inline src/dev/dev_command.ts:43]: If `fresh.gen.ts` is not present on disk, this will throw. Is it handled anywhere?

File: src/server/boot.ts [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+        await bootServer(handler, { ...opts, port });
+        firstError = undefined;
+        break;
+      } catch (err) {
+        if (err instanceof Deno.errors.AddrInUse) {
+          // Throw first EADDRINUSE error
+          // if no port is free
+          if (!firstError) {
+            firstError = err;
+          }
```
Comment (bartlomieju) [inline src/server/boot.ts:45]: Probably not related to this PR but if I read it right this will at most check port `8000` and `8001`. Is that expected?

**Review by bartlomieju — APPROVED** [review]

File: src/dev/dev_command.ts (hunk 1 above)
Comment (marvinhagemeister) [reply src/dev/dev_command.ts:43]: In this dev script we generate the `fresh.gen.ts` manifest a few lines before this one ourselves. I think it's ok to assume that it will be present here.
